import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Input, Button } from "antd";

export default function Home() {
  const [name, setName] = useState("");
  console.log(name);

  return (
    <div className={styles.container}>
      <Head>
        <title>Choose Your Own Adventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Choose Your Own Adventure!</h1>

        <p className={styles.description}>What&apos;s your name? </p>
        <Input
          placeholder="Name"
          size="large"
          style={{ width: "20%" }}
          onChange={(e) => setName(e.target.value)}
        />
        <Button>
          <Link href="/main">Start</Link>
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
